# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46c8c615aba41fdfb0f834c352f8c11cd0c209d49d2bc6b08bc3a6fd30dd378285526063053bdb5deb9884651404bffb0661e10cdb215e450686c6902d44e63c

test:
  secret_key_base: 31efaca404456e8e10f5183f994666a8e0ba794d05e062f4ff0a68d73ed496c27123122c5e95d8a55888ff294dc7d5af2964c0bd816a5cef17d1e54ca5cff2ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
